# Generated by Django 2.2.6 on 2019-12-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avishan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttrack',
            name='view_name',
            field=models.CharField(blank=True, default='NOT_AVAILABLE', max_length=255, null=True),
        ),
    ]
