# Generated by Django 2.2.6 on 2019-10-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avishan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='token_valid_seconds',
            field=models.BigIntegerField(blank=True, default=1800),
        ),
    ]
