# Generated by Django 2.2.6 on 2019-12-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avishan', '0002_requesttrack_view_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='phonepasswordauthenticate',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_authenticates', to='avishan.Phone'),
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('tried_codes', models.TextField(blank=True, default='')),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='avishan.Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
