# Generated by Django 2.2.6 on 2019-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avishan', '0002_usergroup_token_valid_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailpasswordauthenticate',
            name='is_login',
        ),
        migrations.RemoveField(
            model_name='phonepasswordauthenticate',
            name='is_login',
        ),
        migrations.AddField(
            model_name='emailpasswordauthenticate',
            name='last_logout',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='phonepasswordauthenticate',
            name='last_logout',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
