# Generated by Django 2.2.6 on 2019-10-31 00:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avishan', '0003_auto_20191029_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='base_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avishan.BaseUser'),
        ),
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
