# Generated by Django 2.2.6 on 2019-10-31 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avishan', '0004_auto_20191031_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
